### ISSUE TITLE
Update dev image to latest `uproot` v.5.3.2 or newer

### ISSUE THREAD

**Issue by alexander-held** [usatlas/analysisbase-dask#35]
The latest uproot [`v5.3.2`](https://github.com/scikit-hep/uproot5/releases/tag/v5.3.2) brings very useful new metrics for performance testing and sanity checks https://github.com/scikit-hep/uproot5/pull/1156.

**Comment by matthewfeickert** [comment]
Not sure why this didn't get closed, but this is resolved by PR #36.
