### ISSUE TITLE
Can no longer spawn cluster with latest dask-kubernetes

### ISSUE THREAD

**Issue by alexander-held** [usatlas/analysisbase-dask#49]
I believe #48 may have broken the way we spawn clusters through the widget. Attempting to do so at UChicago with AB-dev results in

> Cluster Start Error
module ‘dask_kubernetes’ has no attribute ‘KubeCluster’

and looking at https://github.com/dask/dask-kubernetes/releases/tag/2024.5.0 where I see

> So it feels like the time to finally retire the classic KubeCluster implementation along with the HelmCluster.

I suspect that the update to `dask-kubernetes` is the reason. Maybe some JupyterLab integration would need to be updated accordingly, or perhaps some other backend thing, but for now I think it would be good to revert the change.

**Comment by matthewfeickert** [comment]
Resolved by https://github.com/usatlas/analysisbase-dask/commit/08ef550832c24141e62e1eb78a16b6a513f9d349
