### ISSUE TITLE
Switch to uproot 5.3.8rc1 in AB-dev

### ISSUE THREAD

**Issue by alexander-held** [usatlas/analysisbase-dask#54]
The lastest uproot RC https://pypi.org/project/uproot/5.3.8rc1/ brings us https://github.com/scikit-hep/uproot5/pull/1198 which we expect may have some benefits for 200 Gbps testing. More context on Slack: https://iris-hep.slack.com/archives/C03UA418VJ8/p1715296044867869.

**Comment by matthewfeickert** [comment]
Resolved by PR #55
