### ISSUE TITLE
Update AB-dev for PHYSLITE reading

### ISSUE THREAD

**Issue by alexander-held** [usatlas/analysisbase-dask#60]
To read with PHYSLITE schema for 200 Gbps we need fixes for https://github.com/scikit-hep/uproot5/issues/1267, which are provided in the latest `uproot` 5.3.11, as well as https://github.com/CoffeaTeam/coffea/pull/1156 (and in principle https://github.com/CoffeaTeam/coffea/pull/1169, though technically not needed).

Given some things we see at UNL and don't understand yet, I think it would be best to only update uproot and coffea and not touch other dependencies (dask in particular).

**Comment by matthewfeickert** [comment]
> Given some things we see at UNL and don't understand yet, I think it would be best to only update uproot and coffea and not touch other dependencies (dask in particular).

We need for things to get upgraded before we can upgrade Dask regardless

https://github.com/usatlas/analysisbase-dask/blob/cc502a5a6753fd1987bb4c09c62111d0e69af324/docker/requirements.txt#L2-L4

@ivukotic can comment here about the status of Issue https://github.com/usatlas/analysisbase-dask-uc/issues/9.

**Comment by matthewfeickert** [comment]
For some reason the 'resolves' keyword isn't working here, so closing manually, but resolved by PR #61.
